name: sam
channels:
  - conda-forge
dependencies:
  - nifty >=1.2.3
  - imagecodecs
  - openslide-python
  - magicgui
  - shapely
  - napari
  - natsort
  - pip
  - pooch
  - pyqt
  - python-xxhash
  - python-elf >=0.6.1
  - pytorch >=2.5
  - segment-anything
  - torchvision
  - torch_em >=0.7.8
  - tqdm
  - timm
  - xarray <2025.3.0
  - zarr <3.0
  - numpy
  - pre-commit
  - pytest-cov
